#
# This script will tag the repo, compile and zip our software, and publish it as a GitHub Release
#
# see: https://github.com/marketplace/actions/publish-release
#
# Calling other workflows from this workflow:
#  https://docs.github.com/en/actions/learn-github-actions/reusing-workflows


name: Matt is testing workflows
#on:
#  push:
on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Release Version Tag'
        required: true
        default: '1.3.4b' 

# ${{ github.event.inputs.message }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The repo will me tagged at this moment with 'tag'
        tag_name: ${{ github.event.inputs.version_tag }}
        # Releases can be found under this name.
        release_name: "Version ${{ github.event.inputs.version_tag }}"
        draft: true
        prerelease: false
    - name: Get Sources
      uses: actions/checkout@v2
    - name: Compile FLTK
      run: |
        cmake -S . -B build
        cmake --build build
        mv build/spot .
        zip -9 spot.zip spot
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        # upload this file
        asset_path: ./spot.zip
        # and give it that name in the destination
        asset_name: spot.zip
        asset_content_type: application/zip
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
